https://github.com/remix-run/react-router/pull/12440 introduced a fix for tsconfig, however, it broke non-JS routes (like .mdx)
When we have a file `./app/routes/test/index.mdx` which is a route we get the following error:
```
.react-router/types/app/routes/test/+types/index.ts:10:29 - error TS2307: Cannot find module ../index.js or its corresponding type declarations.

10 type Module = typeof import("../index.js")
                               ~~~~~~~~~~~~~
```